In [1]:
import pandas as pd
import os

In [2]:
folder = '../../data/results/'

In [3]:
prefix = 'simulations-manual-rules-symbols'
files = [f'{folder}{file}' for file in os.listdir(folder)if prefix in file]

In [4]:
dfs = [pd.read_csv(file) for file in files]

In [5]:
df = pd.concat(dfs)

In [6]:
df = df.sort_values('Profits', ascending=False).reset_index(drop=True)

In [7]:
df.head(20)

,Periods,Buy rate,Sell rate,Cut loss rate,Amount used,Final amount,Number of trades,Total fees,Profits,Return rate
0,1,-0.030,0.012,0.0200,45206.98,110191.38,279,44206.98,64984.40,143.748598
1,1,-0.025,0.012,0.0200,64392.08,128310.51,384,63392.08,63918.43,99.264428
2,1,-0.030,0.012,0.0250,41635.79,101088.99,275,40635.79,59453.20,142.793496
3,1,-0.025,0.012,0.0250,56127.20,111668.24,374,55127.20,55541.04,98.955658
4,1,-0.030,0.020,0.0300,41902.26,96668.58,253,40902.26,54766.32,130.700158
5,1,-0.025,0.015,0.0250,50589.48,104752.31,362,49589.48,54162.83,107.063425
6,1,-0.030,0.030,0.0200,31241.84,83077.91,243,30241.84,51836.07,165.918749
7,1,-0.030,0.040,0.0300,24377.68,76182.99,199,23377.68,51805.31,212.511240
8,1,-0.030,0.010,0.0200,38977.23,89664.81,283,37977.23,50687.58,130.044080
9,1,-0.030,0.012,0.0300,38068.01,88164.35,268,37068.01,50096.34,131.596950
10,1,-0.030,0.010,0.0250,37134.06,85803.92,279,36134.06,48669.86,131.065281
11,1,-0.030,0.015,0.0250,34049.97,81989.98,268,33049.97,47940.01,140.793105
12,1,-0.025,0.030,0.0200,37364.62,84964.22,298,36364.62,47599.60,127.392169
13,1,-0.030,0.012,0.0175,41012.24,88506.72,282,40012.24,47494.48,115.805623
14,1,-0.025,0.010,0.0200,54405.78,101668.98,393,53405.78,47263.20,86.871652
15,1,-0.025,0.010,0.0250,53027.78,100084.75,383,52027.78,47056.97,88.740223
16,1,-0.030,0.030,0.0250,30170.46,76973.00,237,29170.46,46802.54,155.127035
17,1,-0.030,0.030,0.0300,31762.47,78508.66,227,30762.47,46746.19,147.174291
18,1,-0.025,0.015,0.0200,46967.40,92556.27,373,45967.40,45588.87,97.064922
19,1,-0.030,0.020,0.0250,33036.18,78449.54,258,32036.18,45413.36,137.465530

In [8]:
df.iloc[7]

Periods                 1.00000
Buy rate               -0.03000
Sell rate               0.04000
Cut loss rate           0.03000
Amount used         24377.68000
Final amount        76182.99000
Number of trades      199.00000
Total fees          23377.68000
Profits             51805.31000
Return rate           212.51124
Name: 7, dtype: float64